export const environment = {
  production: true,
  API_URL: 'https://vanavihari.com/zoho-connect',
  zoho_api_url: 'https://www.zohoapis.com/creator/custom/vanavihari/',
 
  // Account_Registration: process.env.Account_Registration,
  // Edit_Profile: process.env.Edit_Profile,
  // Email_Verification: process.env.Email_Verification,
  // Login_Validation: process.env.Login_Validation,
  // Profile_Details: process.env.Profile_Details,
  // Reservation: process.env.Reservation,
  // Reservation_Detail: process.env.Reservation_Detail,
  // Reservation_Histrory: process.env.Reservation_Histrory,
  // Rooms_List: process.env.Rooms_List,
  // Update_Payment_Status: process.env.Update_Payment_Status,
 
  Account_Registration: 'kFs7xRDC5eRPfyCQ0W7yQNCRv',
  Edit_Profile: 'AKSTTeZV7TEPW4xd2JwaVOuYn',
  Email_Verification: 'TJNXwBQpaFWVvUK3ZmKvufVOJ',
  Login_Validation: 'PWu6q9GvYJJjNSnM6UFSU6fSx',
  Profile_Details: '7AwGYAgpPRaOUDEzbqYpeFyvs',
  Reservation: 'TDHrEVmP2ArM1VtEaM1xOdUwF',
  Reservation_Detail: 'UUnFYm7C9NStE1R8U84uWuT1v',
  Reservation_Histrory: 'hxxrtQ7g2t93U1QUbSOq4kj59',
  Rooms_List: 'J4s0fXQ0wuxFDJJ2ns9Gs3GqK',
  Update_Payment_Status: 'PqBnkhW5yqzF1TDKeEVDMNffd',
};
